const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');
const base=process.env.TEST_URL||'http://localhost:8080';const root=process.env.TEST_BASE_PATH||'';
const pass=process.env.PISCINA_DEMO_PASSWORD,adminPass=process.env.PISCINA_DEMO_ADMIN_PASSWORD;
if(!pass||!adminPass)throw Error('Defina as duas senhas de demonstração em variáveis locais. Nunca use produção.');
const out=process.env.TEST_ARTIFACTS||'work/browser';
(async()=>{await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox']});const errors=[];const report=[];const ctx=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'America/Sao_Paulo'});const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));
async function get(action){return (await (await ctx.request.get(base+root+'/api.php?action='+action)).json()).data;}
async function post(action,data,key=crypto.randomUUID()){const meta=await get('meta');const r=await ctx.request.post(base+root+'/api.php?action='+action,{headers:{'X-CSRF-Token':meta.csrf,'Idempotency-Key':key},data});return {status:r.status(),body:await r.json()};}
async function login(email,password){await page.locator('#account-button').click();await page.locator('dialog [name=email]').fill(email);await page.locator('dialog [name=password]').fill(password);await page.locator('dialog form button.primary').click();await page.waitForSelector('.balance-card');}
async function nav(view){await page.locator(`.sidebar [data-view=${view}]`).click();await page.waitForTimeout(250);}
async function submitDialog(){await page.locator('dialog form button.primary').click();}
await page.goto(base+root+'/index.php');await page.waitForSelector('.nft-card');await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
assert.equal((await get('meta')).environment,'demo','Suíte browser exige demo.');
for(const width of [1440,320,360,390,412]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);await page.screenshot({path:out+`/mercado-${width}.png`,fullPage:true});report.push(`Viewport ${width}: sem rolagem horizontal`);}
await page.setViewportSize({width:1440,height:1000});
const anon=await ctx.request.get(base+root+'/api.php?action=dashboard');assert.equal(anon.status(),401);
const csrf=await ctx.request.post(base+root+'/api.php?action=nft.deposit',{data:{nft_id:'1'}});assert.equal(csrf.status(),403);report.push('API: sessão e CSRF obrigatórios');
await login('artista1@demo.invalid',pass);await page.screenshot({path:out+'/portfolio.png',fullPage:true});report.push('Login e portfólio conectados');
await page.locator('.page-heading [data-action=negotiate]').click();await page.locator('dialog [name=side]').selectOption('SELL');await page.locator('dialog [name=counterparty]').fill('3');await page.locator('dialog [name=asset]').selectOption('BYC');await page.locator('dialog [name=quantity]').fill('3');await page.locator('dialog [name=unit_price]').fill('30.00');await submitDialog();await page.waitForSelector('dialog [data-form=confirm]');assert.match(await page.locator('dialog').textContent(),/90,00/);await submitDialog();await page.waitForFunction(()=>!document.querySelector('dialog').open);let dash=await get('dashboard');const proposal=dash.proposals[0];assert.equal(proposal.state,'PARTIAL');assert.equal(dash.balances.BYC.reserved,'300000000');report.push('Proposta guiada reserva apenas o vendedor');
const key=crypto.randomUUID(),payload={proposal_id:proposal.id,version:proposal.current_version};const foreign=await ctx.request.get(base+root+'/api.php?action=operation&id=xxxxxxxx');assert.equal(foreign.status(),404);
await page.locator('#account-button').click();await page.locator('dialog form button').click();await page.waitForFunction(()=>document.querySelector('#account-name').textContent==='Entrar');assert.doesNotMatch(await page.locator('main').textContent(),/Reservado:/);await page.goBack();await page.waitForTimeout(300);assert.doesNotMatch(await page.locator('main').textContent(),/Reservado:/);report.push('Logout e histórico não recuperam carteira privada');
await login('artista2@demo.invalid',pass);await nav('pending');await page.locator(`[data-action=proposal][data-id="${proposal.id}"]`).click();await page.locator('[data-action=proposal-approve]').click();await submitDialog();await page.waitForFunction(()=>!document.querySelector('dialog').open);dash=await get('dashboard');assert.equal(dash.proposals.find(p=>p.id===proposal.id).state,'SETTLED');report.push('Segunda aprovação liquida BYC e mR$');
const market=await get('market');const nft=market.nfts.find(n=>n.state==='POOL');await nav('pool');await page.locator(`[data-action=nft][data-id="${nft.id}"]`).click();await page.locator('[data-action=withdraw]').click();await page.locator('dialog [name=payment]').selectOption('MR');await submitDialog();await submitDialog();await page.waitForFunction(()=>!document.querySelector('dialog').open);assert.equal((await get('nft&id='+nft.id)).owner_id,'3');report.push('Retirada pública por uma modalidade');
await page.locator('#account-button').click();await page.locator('dialog form button').click();await page.waitForFunction(()=>document.querySelector('#account-name').textContent==='Entrar');
await login('admin@demo.invalid',adminPass);await nav('admin');assert.match(await page.locator('main').textContent(),/Reconciliação/);const mint=await post('admin.mint',{password:adminPass,user_id:'2',title:'Obra de teste de imagem',reason:'Teste browser local'});assert.equal(mint.status,200);const newNft=mint.body.data.nft_id;
const p=await post('admin.parameters',{password:adminPass,interval_minutes:1440,first_cutoff:new Date(Date.now()+3000).toISOString(),reason:'Corte diário de homologação local'});assert.equal(p.status,200);await page.screenshot({path:out+'/administracao.png',fullPage:true});await new Promise(r=>setTimeout(r,3200));const tasks=await post('admin.tasks',{password:adminPass});assert.equal(tasks.status,200);report.push('Administração, calendário e execução finita de tarefas');
await page.locator('#account-button').click();await page.locator('dialog form button').click();await page.waitForFunction(()=>document.querySelector('#account-name').textContent==='Entrar');await login('artista1@demo.invalid',pass);
await page.locator(`[data-action=nft][data-id="${newNft}"]`).click();await page.locator('dialog input[type=file]').setInputFiles(out+'/mercado-390.png');await page.locator('dialog [data-form="nft.upload"] button').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);assert.equal((await get('nft&id='+newNft)).image_ready,'1');report.push('Upload real reencodificado e associado');
await nav('pending');const before=(await get('dashboard')).balances.MR.available;await page.locator('[data-action=right]').first().click();await submitDialog();await page.waitForFunction(()=>!document.querySelector('dialog').open);assert(BigInt((await get('dashboard')).balances.MR.available)>BigInt(before));await page.locator('[data-action=fee]').first().click();await submitDialog();await page.waitForFunction(()=>!document.querySelector('dialog').open);report.push('Recebimento bruto e pagamento independente da taxa');
const caches=await page.evaluate(async()=>{const out=[];for(const key of await window.caches.keys()){for(const r of await(await window.caches.open(key)).keys())out.push(r.url);}return out;});assert(caches.length>0);assert(caches.every(u=>!u.includes('api.php')&&!u.includes('index.php')&&!u.includes('image.php')));report.push('Cache contém somente recursos estáticos autorizados');
await ctx.setOffline(true);await page.reload();await page.waitForSelector('h1');assert.match(await page.locator('h1').textContent(),/pausa na conexão/);await page.screenshot({path:out+'/offline.png'});await ctx.setOffline(false);await page.goto(base+root+'/index.php?view=dashboard');await page.waitForSelector('.balance-card');report.push('Offline exibe página neutra, sem carteira cacheada ou envio automático');
const mf=await(await ctx.request.get(base+root+'/manifest.webmanifest')).json();assert.equal(mf.scope,'./');assert.equal(mf.start_url,'./index.php?view=dashboard');assert.equal(mf.icons.length,3);report.push('Manifesto, ícones e start_url de portfólio');
assert.deepEqual(errors,[]);await fs.writeFile(out+'/resultado.json',JSON.stringify({passed:report,errors,mode:'Chromium automatizado; dispositivos reais e instalação standalone não verificados'},null,2));console.log(report.join('\n'));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
