<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
header('Cache-Control: no-store, private');header('X-Content-Type-Options: nosniff');header('Referrer-Policy: no-referrer');header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' blob:; connect-src 'self'; font-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'");
$setupError=false;$user=null;$initial=[];$csrf='';$base='';$view=$_GET['view']??'market';$views=['market','pool','dashboard','pending','history','admin'];if(!in_array($view,$views,true))$view='market';
try {
    $c=config();$base=$c['base_path'];$auth=new Piscina\Auth(db(),$c);$auth->session();$csrf=$auth->csrf();
    try {$user=service()->user($auth->actor());}catch(Piscina\Problem $e){if($e->status!==401)throw $e;}
    $query=new Piscina\Queries(service());
    if(in_array($view,['dashboard','pending','history','admin'],true)&&!$user) $view='login';
    $initial=$view==='pool'?$query->market(['state'=>'POOL']):($view==='market'?$query->market([]):($user&&$view==='dashboard'?$query->dashboard((int)$user['id']):[]));
} catch(Throwable $e) {$setupError=true;error_log('Piscina página: '.$e->getMessage());}
function icon(string $name): string {return '<svg aria-hidden="true" class="icon"><use href="#i-'.h($name).'"/></svg>';}
$baseEsc=h($base);
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#133c32"><meta name="description" content="Descubra arte, encontre contrapartes e participe de um mercado com moeda de simulação."><title>Piscina de Liquidez — Arte em movimento</title><link rel="icon" href="<?= $baseEsc ?>/icons/icon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="<?= $baseEsc ?>/icons/icon-192.png"><link rel="manifest" href="<?= $baseEsc ?>/manifest.php"><link rel="stylesheet" href="<?= $baseEsc ?>/assets/app.css"><script type="module" src="<?= $baseEsc ?>/assets/app.js"></script></head>
<body data-base="<?= $baseEsc ?>" data-initial-view="<?= h($view) ?>" data-csrf="<?= h($csrf) ?>"><a href="#main" class="skip">Ir para o conteúdo</a>
<svg class="sprite" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><symbol id="i-grid" viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></symbol><symbol id="i-pool" viewBox="0 0 24 24"><path d="M2 15q3-4 6 0t6 0t8 0M2 20q3-4 6 0t6 0t8 0M7 10V4a2 2 0 0 1 4 0m2 6V4a2 2 0 0 1 4 0M7 7h6"/></symbol><symbol id="i-wallet" viewBox="0 0 24 24"><path d="M20 7H4a2 2 0 0 1 0-4h13v4M3 5v14a2 2 0 0 0 2 2h15V7m0 5h-6v5h6"/></symbol><symbol id="i-clock" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></symbol><symbol id="i-bell" viewBox="0 0 24 24"><path d="M4 17h16l-2-4V9a6 6 0 0 0-12 0v4l-2 4m6 3h4"/></symbol><symbol id="i-arrow" viewBox="0 0 24 24"><path d="M4 12h16m-6-6 6 6-6 6"/></symbol><symbol id="i-search" viewBox="0 0 24 24"><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></symbol><symbol id="i-shield" viewBox="0 0 24 24"><path d="m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6zM8 12l3 3 5-6"/></symbol><symbol id="i-swap" viewBox="0 0 24 24"><path d="M3 7h18m-5-5 5 5-5 5M21 17H3m5 5-5-5 5-5"/></symbol><symbol id="i-down" viewBox="0 0 24 24"><path d="m6 9 6 6 6-6"/></symbol><symbol id="i-install" viewBox="0 0 24 24"><path d="M12 3v12m-5-5 5 5 5-5M4 15v6h16v-6"/></symbol></svg>
<aside class="sidebar"><a class="brand" href="<?= $baseEsc ?>/index.php?view=market"><span class="brand-mark"><i></i><i></i><i></i></span><span>Piscina<span class="brand-sub">DE LIQUIDEZ</span></span></a><div class="workspace-label">SEU MERCADO DE ARTE <span>↗</span></div><nav aria-label="Navegação principal">
<?php foreach(['market'=>['grid','Explorar mercado'],'pool'=>['pool','Piscina'],'dashboard'=>['wallet','Meu portfólio'],'pending'=>['bell','Pendências'],'history'=>['clock','Histórico']] as $key=>$item):?><a class="nav-link <?= $view===$key?'active':'' ?>" href="<?= $baseEsc ?>/index.php?view=<?= $key ?>" data-view="<?= $key ?>"><?= icon($item[0]) ?><span><?= $item[1] ?></span><?= $key==='market'?'<span class="nav-dot"></span>':'' ?></a><?php endforeach;?>
<a class="nav-link" href="<?= $baseEsc ?>/index.php?view=admin" data-view="admin" id="admin-link" <?= ($user['role']??'')==='admin'?'':'hidden' ?>><?= icon('shield') ?><span>Administração</span></a></nav>
<div class="sidebar-bottom"><div class="simulation-card"><span class="live-dot"></span><strong>Um mercado, novas possibilidades.</strong><p>Arte e colaboração com moeda de simulação.</p><span class="tiny">Sem conversão para dinheiro real</span></div><button class="install-btn" data-action="install"><?= icon('install') ?> Instalar app <span>↗</span></button><div class="side-footer"><span>Moeda simulada · mR$</span><span>v1.0</span></div></div></aside>
<div class="app-shell"><header class="topbar"><div class="breadcrumb"><span>Piscina de Liquidez</span><span>/</span><strong id="crumb">Explorar</strong></div><div class="top-actions"><span class="status-pill" id="network"><i></i> Conectado</span><button class="icon-button" data-view="pending" aria-label="Ver pendências"><?= icon('bell') ?></button><button class="user-button" id="account-button" data-action="account"><span class="avatar"><?= h(mb_substr($user['display_name']??'P',0,1)) ?></span><span id="account-name"><?= h($user['display_name']??'Entrar') ?></span><?= icon('down') ?></button></div></header>
<div class="environment-banner" id="environment-banner" hidden></div><div class="offline-banner" id="offline-banner" hidden>Você está offline. Operações precisam de conexão e nova revisão.</div>
<main id="main" tabindex="-1">
<?php if($setupError):?><section class="setup-panel"><span class="eyebrow">PISCINA DE LIQUIDEZ</span><h1>Seu mercado está quase pronto.</h1><p>Configure a conexão MySQL e a instalação privada para começar. O diagnóstico completo fica no log do servidor.</p><p>Consulte o guia <strong>DEPLOY_SUPERDOMINIOS.md</strong> incluído no pacote.</p></section>
<?php elseif($view==='login'):?><section class="auth-panel"><span class="eyebrow">BEM-VINDO À PISCINA</span><h1>Entre para participar.</h1><p>Seu portfólio, propostas e próximos passos em um só lugar.</p><form data-form="auth.login" method="post" action="<?= $baseEsc ?>/form.php"><input type="hidden" name="csrf" value="<?= h($csrf) ?>"><input type="hidden" name="action" value="auth.login"><label>E-mail<input name="email" type="email" autocomplete="email" required></label><label>Senha<input name="password" type="password" autocomplete="current-password" required></label><button class="primary" type="submit">Entrar <?= icon('arrow') ?></button></form><button class="text-button" data-action="register">Criar conta</button><button class="text-button" data-action="reset">Esqueci minha senha</button></section>
<?php elseif(in_array($view,['market','pool'],true)):?>
<section class="page-heading"><div><span class="eyebrow">ARTE, PESSOAS E POSSIBILIDADES</span><h1><?= $view==='pool'?'A piscina está aberta.':'Arte em movimento.' ?></h1><p><?= $view==='pool'?'Descubra obras disponíveis para retirada pública.':'Descubra obras. Encontre sua contraparte. Faça parte.' ?></p></div><div class="trade-split"><button class="primary" data-action="negotiate"><?= icon('swap') ?> NEGOCIAR</button><button class="primary split-arrow" data-action="shortcuts" aria-label="Abrir atalhos de negociação" aria-expanded="false"><?= icon('down') ?></button></div></section>
<section class="hero"><div class="hero-copy"><span class="hero-label"><span class="live-dot"></span> <?= $view==='pool'?'CUSTÓDIA COMPARTILHADA':'UM NOVO JEITO DE PARTICIPAR' ?></span><h2>Uma obra encontra<br>seu próximo capítulo.</h2><p>Deposite uma NFT, receba 10 BYC e uma cota.<br>Explore a piscina e conecte-se com outros participantes.</p><a class="hero-link" href="<?= $baseEsc ?>/index.php?view=pool" data-view="pool">Conhecer a piscina <?= icon('arrow') ?></a></div><div class="hero-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="art-sphere"></div><span class="art-label">ARTE EM CIRCULAÇÃO <span>↗</span></span><span class="art-coordinate">PL / 001</span></div></section>
<section class="market-stats" aria-label="Indicadores do mercado"><?php foreach(['pool_nfts'=>['pool','Obras na piscina'],'shares'=>['grid','Cotas em circulação'],'participants'=>['wallet','Participantes'],'trades'=>['swap','Negócios concluídos']] as $key=>$info):?><div class="stat"><?= icon($info[0]) ?><div><span><?= $info[1] ?></span><strong data-stat="<?= $key ?>"><?= h($initial['stats'][$key]??'0') ?></strong></div></div><?php endforeach;?></section>
<section class="catalog"><div class="section-top"><div class="tabs" role="group" aria-label="Filtrar ativos"><button class="tab active" data-filter="NFT">Obras <span id="nft-count"><?= count($initial['nfts']??[]) ?></span></button><button class="tab" data-filter="BYC">Bytcoin</button><button class="tab" data-filter="SHARE">Cotas</button><button class="tab" data-filter="people">Pessoas</button></div><label class="search-box"><?= icon('search') ?><input type="search" id="search" placeholder="Buscar obras ou pessoas" aria-label="Buscar obras ou pessoas"></label></div><div class="catalog-label"><span id="catalog-title"><?= $view==='pool'?'Disponíveis na piscina':'Explore o mercado' ?></span><span>Mais recentes <?= icon('down') ?></span></div><div class="nft-grid" id="catalog-grid"><?php foreach($initial['nfts']??[] as $n):?><button class="nft-card" data-action="nft" data-id="<?= h($n['id']) ?>"><div class="art-frame"><img src="<?= $baseEsc ?>/image.php?id=<?= h($n['id']) ?>&thumb=1" alt="<?= h($n['title']) ?>" width="480" height="480" loading="lazy"><span class="art-badge"><?= $n['state']==='POOL'?'Na piscina':'À venda' ?></span><span class="art-number">#<?= h($n['id']) ?></span></div><div class="nft-copy"><span class="creator"><?= h($n['creator_name']) ?></span><h3><?= h($n['title']) ?></h3><div class="card-line"><span><?= $n['state']==='POOL'?'Retirada pública':'Negociação bilateral' ?></span><strong><?= $n['state']==='POOL'?'11 BYC ↗':'Ver oferta ↗' ?></strong></div></div></button><?php endforeach;?></div><?php if(empty($initial['nfts'])):?><div class="empty" id="initial-empty"><?= icon('pool') ?><h3>O próximo capítulo começa com você.</h3><p>As obras publicadas e depositadas aparecerão aqui.</p><button class="secondary" data-action="register">Participar do mercado</button></div><?php endif;?><button class="secondary load-more" id="load-more" hidden>Carregar mais</button></section>
<section class="activity"><div class="section-title"><h2>O mercado acontece aqui.</h2><span class="muted">Negócios concluídos</span></div><div id="feed"><p class="muted">A atividade pública aparece após a conclusão de um negócio.</p></div></section><footer class="page-footer"><span>Arte em circulação. Pessoas em conexão.</span><span>mR$ é moeda de simulação, sem conversão para dinheiro real.</span></footer>
<?php elseif($view==='dashboard'):?><section class="page-heading"><div><span class="eyebrow">SEU ESPAÇO NA PISCINA</span><h1>Meu portfólio.</h1><p>Saldos, obras e próximos passos.</p></div><button class="primary" data-action="negotiate">NEGOCIAR <?= icon('arrow') ?></button></section><div class="balance-grid"><?php foreach(['MR'=>'mR$','BYC'=>'BYC','SHARE'=>'Cotas'] as $asset=>$label):?><article class="balance-card"><span><?= $label ?></span><strong><?= h(formatAmount($initial['balances'][$asset]['available']??'0',$asset)) ?></strong><p>Reservado: <?= h(formatAmount($initial['balances'][$asset]['reserved']??'0',$asset)) ?></p></article><?php endforeach;?></div><div id="dashboard-content"><p>Use a navegação para consultar pendências e histórico.</p></div>
<?php else:?><div class="loading">Carregando sua área…</div><?php endif;?></main>
</div><nav class="mobile-nav" aria-label="Navegação móvel"><?php foreach(['market'=>['grid','Explorar'],'pool'=>['pool','Piscina'],'dashboard'=>['wallet','Portfólio'],'pending'=>['bell','Pendências']] as $k=>$i):?><a href="<?= $baseEsc ?>/index.php?view=<?= $k ?>" data-view="<?= $k ?>"><?= icon($i[0]) ?><span><?= $i[1] ?></span></a><?php endforeach;?></nav>
<dialog id="dialog"><div class="dialog-top"><span class="eyebrow" id="dialog-eyebrow">PISCINA DE LIQUIDEZ</span><button class="icon-button" data-action="close" aria-label="Fechar">×</button></div><div id="dialog-content"></div></dialog><div id="toast" role="status" aria-live="polite" hidden></div><div id="update-banner" hidden>Uma atualização está disponível. <button class="text-button" id="apply-update">Atualizar app</button></div>
</body></html>
