CREATE TABLE IF NOT EXISTS schema_migrations (version VARCHAR(80) PRIMARY KEY, applied_at DATETIME(6) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS economic_gate (id INT PRIMARY KEY, sequence_no BIGINT NOT NULL DEFAULT 0) ENGINE=InnoDB;
INSERT IGNORE INTO economic_gate(id) VALUES(1);
CREATE TABLE IF NOT EXISTS users (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 display_name VARCHAR(80) NOT NULL, auth_version INT NOT NULL DEFAULT 1, role VARCHAR(20) NOT NULL DEFAULT 'participant', status VARCHAR(20) NOT NULL DEFAULT 'pending',
 email_verified_at DATETIME(6) NULL, approved_at DATETIME(6) NULL, created_at DATETIME(6) NOT NULL,
 INDEX(status,id), INDEX(display_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS auth_tokens (id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL,kind VARCHAR(20) NOT NULL,token_hash CHAR(64) NOT NULL UNIQUE,expires_at DATETIME(6) NOT NULL,used_at DATETIME(6),FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS rate_limits (bucket CHAR(64) PRIMARY KEY,attempts INT NOT NULL,expires_at DATETIME(6) NOT NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS parameter_versions (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,author_id BIGINT NULL,initial_credit BIGINT NOT NULL,withdraw_money BIGINT NOT NULL,distribution_base BIGINT NOT NULL,admin_fee BIGINT NOT NULL,
 interval_minutes INT NULL,first_cutoff DATETIME(6) NULL,effective_at DATETIME(6) NOT NULL,reason VARCHAR(255) NOT NULL,
 FOREIGN KEY(author_id) REFERENCES users(id)
) ENGINE=InnoDB;
INSERT IGNORE INTO parameter_versions(id,initial_credit,withdraw_money,distribution_base,admin_fee,effective_at,reason) VALUES(1,160000,140000,20000,10000,UTC_TIMESTAMP(6),'Parâmetros iniciais da especificação');
CREATE TABLE IF NOT EXISTS decision_versions (id BIGINT AUTO_INCREMENT PRIMARY KEY,author_id BIGINT NOT NULL,policy LONGTEXT NOT NULL,created_at DATETIME(6) NOT NULL,FOREIGN KEY(author_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS accounts (id BIGINT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(100) NOT NULL UNIQUE,user_id BIGINT NULL,asset VARCHAR(8) NOT NULL,purpose VARCHAR(30) NOT NULL,balance BIGINT NOT NULL DEFAULT 0,FOREIGN KEY(user_id) REFERENCES users(id),INDEX(user_id,asset,purpose)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS operations (id CHAR(32) PRIMARY KEY,actor_id BIGINT NOT NULL,action VARCHAR(60) NOT NULL,idempotency_key VARCHAR(80) NOT NULL,payload_hash CHAR(64) NOT NULL,result LONGTEXT NULL,effective_at DATETIME(6) NOT NULL,sequence_no BIGINT NOT NULL,UNIQUE(actor_id,action,idempotency_key),FOREIGN KEY(actor_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS ledger_transactions (id BIGINT AUTO_INCREMENT PRIMARY KEY,operation_id CHAR(32) NULL,kind VARCHAR(40) NOT NULL,reference VARCHAR(100) NOT NULL UNIQUE,created_at DATETIME(6) NOT NULL,FOREIGN KEY(operation_id) REFERENCES operations(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS ledger_entries (id BIGINT AUTO_INCREMENT PRIMARY KEY,transaction_id BIGINT NOT NULL,account_id BIGINT NOT NULL,amount BIGINT NOT NULL,FOREIGN KEY(transaction_id) REFERENCES ledger_transactions(id),FOREIGN KEY(account_id) REFERENCES accounts(id),INDEX(account_id,id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS initial_grants (user_id BIGINT PRIMARY KEY,parameter_id BIGINT NOT NULL,operation_id CHAR(32) NOT NULL UNIQUE,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(parameter_id) REFERENCES parameter_versions(id),FOREIGN KEY(operation_id) REFERENCES operations(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS nfts (id BIGINT AUTO_INCREMENT PRIMARY KEY,creator_id BIGINT NOT NULL,owner_id BIGINT NULL,title VARCHAR(120) NOT NULL,state VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',image_path VARCHAR(100) NULL,thumbnail_path VARCHAR(100) NULL,image_sha CHAR(64) NULL,reserved_proposal BIGINT NULL,created_at DATETIME(6) NOT NULL,FOREIGN KEY(creator_id) REFERENCES users(id),FOREIGN KEY(owner_id) REFERENCES users(id),INDEX(state,id),INDEX(owner_id,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS nft_events (id BIGINT AUTO_INCREMENT PRIMARY KEY,nft_id BIGINT NOT NULL,actor_id BIGINT NOT NULL,kind VARCHAR(30) NOT NULL,from_user BIGINT NULL,to_user BIGINT NULL,operation_id CHAR(32) NOT NULL,effective_at DATETIME(6) NOT NULL,FOREIGN KEY(nft_id) REFERENCES nfts(id),FOREIGN KEY(actor_id) REFERENCES users(id),FOREIGN KEY(operation_id) REFERENCES operations(id),INDEX(nft_id,id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS deposits (id BIGINT AUTO_INCREMENT PRIMARY KEY,nft_id BIGINT NOT NULL,user_id BIGINT NOT NULL,operation_id CHAR(32) NOT NULL UNIQUE,created_at DATETIME(6) NOT NULL,FOREIGN KEY(nft_id) REFERENCES nfts(id),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(operation_id) REFERENCES operations(id),INDEX(nft_id,id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS proposals (id BIGINT AUTO_INCREMENT PRIMARY KEY,buyer_id BIGINT NOT NULL,seller_id BIGINT NOT NULL,current_version INT NOT NULL DEFAULT 1,state VARCHAR(30) NOT NULL DEFAULT 'WAITING',created_at DATETIME(6) NOT NULL,settled_at DATETIME(6) NULL,FOREIGN KEY(buyer_id) REFERENCES users(id),FOREIGN KEY(seller_id) REFERENCES users(id),INDEX(buyer_id,state,id),INDEX(seller_id,state,id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS proposal_versions (proposal_id BIGINT NOT NULL,version INT NOT NULL,author_id BIGINT NOT NULL,asset VARCHAR(8) NOT NULL,nft_id BIGINT NULL,quantity BIGINT NOT NULL,unit_price BIGINT NOT NULL,total BIGINT NOT NULL,expires_at DATETIME(6) NOT NULL,rounding_rule VARCHAR(40) NOT NULL DEFAULT 'HALF_UP_CENT',created_at DATETIME(6) NOT NULL,PRIMARY KEY(proposal_id,version),FOREIGN KEY(proposal_id) REFERENCES proposals(id),FOREIGN KEY(author_id) REFERENCES users(id),FOREIGN KEY(nft_id) REFERENCES nfts(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS approvals (proposal_id BIGINT NOT NULL,version INT NOT NULL,user_id BIGINT NOT NULL,created_at DATETIME(6) NOT NULL,PRIMARY KEY(proposal_id,version,user_id),FOREIGN KEY(proposal_id,version) REFERENCES proposal_versions(proposal_id,version),FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS reservations (id BIGINT AUTO_INCREMENT PRIMARY KEY,proposal_id BIGINT NOT NULL,version INT NOT NULL,user_id BIGINT NOT NULL,asset VARCHAR(8) NOT NULL,amount BIGINT NOT NULL,state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',UNIQUE(proposal_id,version,user_id),FOREIGN KEY(proposal_id,version) REFERENCES proposal_versions(proposal_id,version),FOREIGN KEY(user_id) REFERENCES users(id),INDEX(state,proposal_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS settlements (proposal_id BIGINT PRIMARY KEY,version INT NOT NULL,operation_id CHAR(32) NOT NULL UNIQUE,FOREIGN KEY(proposal_id) REFERENCES proposals(id),FOREIGN KEY(operation_id) REFERENCES operations(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS listings (id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL,side VARCHAR(8) NOT NULL,asset VARCHAR(8) NOT NULL,nft_id BIGINT NULL,quantity BIGINT NOT NULL,unit_price BIGINT NOT NULL,state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',expires_at DATETIME(6) NOT NULL,created_at DATETIME(6) NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(nft_id) REFERENCES nfts(id),INDEX(state,asset,id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS periods (id BIGINT AUTO_INCREMENT PRIMARY KEY,cutoff_at DATETIME(6) NOT NULL UNIQUE,parameter_id BIGINT NOT NULL,nft_count INT NOT NULL,total_shares BIGINT NOT NULL,distribution_total BIGINT NOT NULL,state VARCHAR(20) NOT NULL DEFAULT 'SNAPSHOT',processing_started_at DATETIME(6) NULL,processed_at DATETIME(6) NULL,gate_sequence BIGINT NOT NULL,FOREIGN KEY(parameter_id) REFERENCES parameter_versions(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS period_snapshots (period_id BIGINT NOT NULL,user_id BIGINT NOT NULL,shares BIGINT NOT NULL,eligible TINYINT NOT NULL,processed TINYINT NOT NULL DEFAULT 0,PRIMARY KEY(period_id,user_id),FOREIGN KEY(period_id) REFERENCES periods(id),FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS rights (id BIGINT AUTO_INCREMENT PRIMARY KEY,period_id BIGINT NOT NULL,user_id BIGINT NOT NULL,amount BIGINT NOT NULL,state VARCHAR(20) NOT NULL DEFAULT 'PENDING',accepted_operation CHAR(32) NULL UNIQUE,UNIQUE(period_id,user_id),FOREIGN KEY(period_id) REFERENCES periods(id),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(accepted_operation) REFERENCES operations(id),INDEX(user_id,state,id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS fees (id BIGINT AUTO_INCREMENT PRIMARY KEY,period_id BIGINT NOT NULL,user_id BIGINT NOT NULL,amount BIGINT NOT NULL,state VARCHAR(20) NOT NULL DEFAULT 'PENDING',paid_operation CHAR(32) NULL UNIQUE,UNIQUE(period_id,user_id),FOREIGN KEY(period_id) REFERENCES periods(id),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(paid_operation) REFERENCES operations(id),INDEX(user_id,state,id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit_events (id BIGINT AUTO_INCREMENT PRIMARY KEY,actor_id BIGINT NULL,operation_id CHAR(32) NULL,kind VARCHAR(60) NOT NULL,data LONGTEXT NOT NULL,created_at DATETIME(6) NOT NULL,FOREIGN KEY(actor_id) REFERENCES users(id),FOREIGN KEY(operation_id) REFERENCES operations(id),INDEX(kind,id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS notifications (id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL,message VARCHAR(255) NOT NULL,created_at DATETIME(6) NOT NULL,read_at DATETIME(6) NULL,FOREIGN KEY(user_id) REFERENCES users(id),INDEX(user_id,id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS outbox (id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL,subject VARCHAR(190) NOT NULL,body TEXT NOT NULL,state VARCHAR(20) NOT NULL DEFAULT 'PENDING',attempts INT NOT NULL DEFAULT 0,next_attempt_at DATETIME(6) NOT NULL,locked_until DATETIME(6) NULL,last_error VARCHAR(255) NULL,FOREIGN KEY(user_id) REFERENCES users(id),INDEX(state,next_attempt_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS task_runs (id BIGINT AUTO_INCREMENT PRIMARY KEY,started_at DATETIME(6) NOT NULL,finished_at DATETIME(6) NULL,status VARCHAR(20) NOT NULL,summary LONGTEXT NULL) ENGINE=InnoDB;
INSERT IGNORE INTO schema_migrations(version,applied_at) VALUES('001_initial',UTC_TIMESTAMP(6));
